version: '3'
volumes:
  postgres_data: {}

services:
  db:
    image: postgres:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports:
      - 3000:3000
    links:
      - db 
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: newpass