default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: magnifier_development

test:
  <<: *default
  database: magnifier_test

production:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST") %>
  user: <%= ENV.fetch("DATABASE_USER") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  database: magnifier_production
